(maint) Move macos tests to github actions
In order to keep them, while also keeping them from holding up
completion in travis, and to run them faster (hardware, etc. appears
to be better), move the macos tests to github actions.

Move the "CI specific" code from ext/travisci to ci/...  Prefix the
completely travis-specific commands with travis-,
e.g. ci/bin/travis-on-success.

Move all the common test "work" from the .travis.yml aliases into
"ci/bin/prep-and-run-in (github|travis|...) ..." and ci/bin/run

Keep non-CI specific code in ext/bin, e.g. prep-debianish-root,
prep-debianish, and prep-macos.  These also provide at least some
clearer evidence about what anyone (outside CI) might need to install
on the platforms to run the tests.

Separate the root and non-root actions into two scripts so that
they're independent of the mechanism used to become root: sudo, su,
ssh, etc.

Allow core and ext tests to be run independently, i.e. not just via
core+ext.

diff --git a/ext/bin/run-external-tests b/ext/bin/run-external-tests
--- a/ext/bin/run-external-tests
+++ b/ext/bin/run-external-tests
@@ -5,7 +5,11 @@ set -ueo pipefail
 failures=0
 
 failure() {
-    echo "===== $(tput setaf 1)FAILED:$(tput sgr 0) $@" 1>&2
+    if test "$TERM"; then
+        echo "===== $(tput setaf 1)FAILED:$(tput sgr 0) $@" 1>&2
+    else
+        echo "===== FAILED: $@" 1>&2
+    fi
     ((failures++)) || true
 }
 
@@ -37,7 +41,10 @@ run ext/test/schema-mismatch-causes-pdb-shutdown
 if test "$failures" -eq 0; then
     echo "failures: $failures" 1>&2
     exit 0
-else
+elif test "$TERM"; then
     echo "$(tput setaf 1)failures: $failures$(tput sgr 0)" 1>&2
+    exit 2
+else
+    echo "failures: $failures" 1>&2
     exit 2
 fi
