Rebase init script for the one actually used
Previously I had grabbed the wrong init script for puppetdb.  It was an
older copy.  This one removes usage of daemonize.rb and complies with
debian standards.

This is largely taken from Ben with a few updates/changes to make it a
bit more generic and named properly for puppetdb.  I also updated the
default file which is used in /etc/default and /etc/sysconfig.  Since no
Red Hat init script is written yet, I overwrote the one with this new
debian one as a starting point.

Signed-off-by: Michael Stahnke <stahnma@puppetlabs.com>

diff --git a/ext/templates/init_debian.erb b/ext/templates/init_debian.erb
--- a/ext/templates/init_debian.erb
+++ b/ext/templates/init_debian.erb
@@ -1,106 +1,167 @@
 #! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          <%= @name %>
-# Required-Start:    $network $named $remote_fs $syslog
-# Required-Stop:     $network $named $remote_fs $syslog
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
+# Short-Description: <%= @name -%> stored config server
+# Description:       Start <%= @name -%> daemon placed in /etc/init.d.
 ### END INIT INFO
-#
-. /etc/default/<%= @name %>
+
+# Author: Ben Hughes <ben@puppetlabs.com>
+#         Michael Stahnke <stahnma@puppetlabs.com>
+# Copyright 2012 Puppet Labs
 
 
-DIR="<%= @install_dir %>"
-DAEMON="$DIR/daemonize.rb"
-JARFILE="$DIR/puppetdb.jar"
-DAEMON_OPTS="${JAVA_BIN} ${JAVA_ARGS}  -jar $JARFILE services -c <%= @config_dir -%>/config.ini"
-NAME=<%= @name  %>
-DESC="PuppetDB"
-PIDFILE="<%= @install_dir  %>/${NAME}.pid"
+# You should only need to edit the default/<%= @name -%> file and not
+#   this init script directly
+if [ -r "/etc/default/<%= @name -%>" ] ; then
+  . /etc/default/<%= @name %>
+else
+  exit 1
+fi
 
-test -x $DAEMON || exit 0
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+NAME=<%= @name %>
+DESC="<%= @name -%> centralized storage daemon"
+JARFILE="puppetdb.jar"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
+JAVA_ARGS="${JAVA_ARGS} -jar ${INSTALL_DIR}/${JARFILE} services -c ${CONFIG} "
+EXTRA_ARGS="--chuid $USER --background --make-pidfile"
+
+# Exit if the package is not installed
+[ -x "$JAVA_BIN" ] || exit 0
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
 . /lib/lsb/init-functions
 
-is_true() {
-    if [ "x$1" = "xtrue" -o "x$1" = "xyes" -o "x$1" = "x0" ] ; then
-        return 0
-    else
-        return 1
-    fi
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+    # We need to do something with the log file...
+
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start $EXTRA_ARGS --quiet --pidfile $PIDFILE --chdir $INSTALL_DIR --exec $JAVA_BIN --test > /dev/null \
+        || return 1
+    start-stop-daemon --start $EXTRA_ARGS --quiet --pidfile $PIDFILE --chdir $INSTALL_DIR --exec $JAVA_BIN -- \
+        $JAVA_ARGS \
+        || return 2
+    # Add code here, if necessary, that waits for the process to be ready
+    # to handle requests from services started subsequently which depend
+    # on this one.  As a last resort, sleep for some time.
+
+    # <%= @name -%> takes a long time to spin up on ningyo, waiting for it
+    # would be bad.
 }
 
-reload() {
-    start-stop-daemon --stop --quiet --signal HUP --pidfile $PIDFILE
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+    RETVAL="$?"
+    [ "$RETVAL" = 2 ] && return 2
+    # Wait for children to finish too if this is a daemon that forks
+    # and if the daemon is only ever run from this initscript.
+    # If the above conditions are not satisfied then add some other code
+    # that waits for the process to drop all resources that could be
+    # needed by services started subsequently.  A last resort is to
+    # sleep for some time.
+    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $JAVA_BIN
+    [ "$?" = 2 ] && return 2
+    # Many daemons don't delete their pidfiles when they exit.
+    rm -f $PIDFILE
+    return "$RETVAL"
 }
 
-start() {
-    start-stop-daemon --start --quiet --pidfile $PIDFILE \
-        --startas $DAEMON -- $DAEMON_OPTS 1> $DIR/stdout.log 2> $DIR/stderr.log &
-}
-
-stop() {
-    # wait until really stopped
-    PID=`cat $PIDFILE 2> /dev/null`
-
-    start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/STOP/30/KILL/30 --pidfile $PIDFILE
-
-    if [ -n "${PID:-}" ]; then
-        i=0
-        while kill -0 "${PID:-}" 2> /dev/null;  do
-            if [ $i = '60' ]; then
-                kill -9 $PID
-                rm -f $PIDFILE
-                break;
-            else
-                if [ $i = '0' ]; then
-                    echo -n " ... waiting "
-                else
-                    echo -n "."
-                fi
-                i=$(($i+1))
-                sleep 1
-            fi
-        done
-    fi
-}
-
-status() {
-    if [ -f "${PIDFILE}" ]; then
-        status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}"
-    else
-        if $(ps -ef | grep "$JARFILE" | grep -v grep 2>&1 > /dev/null); then
-            log_daemon_msg "${NAME} is running"
-            return 0
-        fi; 
-        log_daemon_msg "${NAME} is not running"
-        return 1
-    fi
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+    #
+    # If the daemon can reload its configuration without
+    # restarting (for example, when it is sent a SIGHUP),
+    # then implement that here.
+    #
+    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+    return 0
 }
 
 case "$1" in
-    start)
-    log_begin_msg "Starting $DESC"
-    start
-    log_end_msg $?
+  start)
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
     ;;
-    stop)
-    log_begin_msg "Stopping $DESC"
-    stop
-    log_end_msg $?
+  stop)
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
     ;;
-    status)
-        status
-    ;;
-    restart|force-reload)
-    log_begin_msg "Restarting $DESC"
-    stop
-    sleep 1
-    start
-    log_end_msg $?
+  status)
+       status_of_proc "$JAVA_BIN" "$NAME" && exit 0 || exit $?
+       ;;
+  #reload|force-reload)
+    #
+    # If do_reload() is not implemented then leave this commented out
+    # and leave 'force-reload' as an alias for 'restart'.
+    #
+    #log_daemon_msg "Reloading $DESC" "$NAME"
+    #do_reload
+    #log_end_msg $?
+    #;;
+  restart|force-reload)
+    #
+    # If the "reload" option is implemented then remove the
+    # 'force-reload' alias
+    #
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;; # Old process is still running
+            *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
     ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|force-reload|reload}" >&2
-    exit 1
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    exit 3
     ;;
 esac
+
+:
